# Generated by Django 2.2 on 2019-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Des', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Detalis',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=30)),
                ('Gen', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=30)),
                ('Blood', models.CharField(max_length=30)),
                ('Addres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.ImageField(upload_to='images/')),
                ('prescription', models.ImageField(upload_to='images/')),
                ('OtherAtachment', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('Hb', models.CharField(max_length=30)),
                ('GlbLevel', models.CharField(max_length=30)),
                ('HlBac', models.CharField(max_length=30)),
                ('Heatbeet', models.CharField(max_length=30)),
                ('Oxeygenlevel', models.CharField(max_length=30)),
                ('Bmi', models.CharField(max_length=30)),
            ],
        ),
    ]
